### ISSUE TITLE
ParseBytes method error every time after the first error

### ISSUE THREAD

**Issue by canuran** [goccy/go-graphviz#60]
graphviz.ParseBytes([]byte(`digraph{a->b;b->d;a->c;c->d;}`)) // success
	graphviz.ParseBytes([]byte(`digraph{a->b;b->d;a->c;c->d;}www`)) // error
	graphviz.ParseBytes([]byte(`digraph{a->b;b->d;a->c;c->d;}`)) // error
	graphviz.ParseBytes([]byte(`digraph{a->b;b->d;a->c;c->d;}`)) // error
	graphviz.ParseBytes([]byte(`digraph{a->b;b->d;a->c;c->d;}`)) // error

**Comment by codyaray** [comment]
I just ran into the same issue. It seems like `Aglasterr()` is implemented using a file on disk (global!) which is never cleaned up. There is an `agreseterrors()` in the C code, but it's never called... and doesn't look like it removes the file anyway.

**Comment by denk0403** [comment]
This has been driving me insane all week. I thought it was certainly [a Vercel issue](https://github.com/vercel/community/discussions/1482) because I wasn't experiencing it locally, but rather only when I deployed it to Vercel's edge network, but I guess the strange behavior is actually that I wasn't experiencing it locally.

Did anyone find a workaround? If not, I'm willing to try to make a PR with the fix, but I'm not super familiar with Go or C.

**Comment by denk0403** [comment]
This issue has been fixed with the merge of 865af03, and can be closed now.

**Comment by goccy** [comment]
v0.1.1 has been released ! Please check 😄
