### ISSUE TITLE
Libexpat before 2.4.5 contains a CVE

### ISSUE THREAD

**Issue by esnible** [goccy/go-graphviz#76]
The "Mend" tool complains about a CVE in the embedded version of Expat. Consider replacing the current Expat source with newer version.

- https://www.mend.io/vulnerability-database/CVE-2022-25235
  - Critical severity

The claim is that
- _xmltok_impl.c_ in Expat (aka libexpat) before 2.4.5 lacks certain validation of encoding, such as checks for whether a UTF-8 character is valid in a certain context.

Here is Expat's fix of the issue
- https://github.com/libexpat/libexpat/commit/3f0a0cb644438d4d8e3294cd0b1245d0edb0c6c6

Go-graphviz is using this version
- https://github.com/goccy/go-graphviz/blob/master/internal/expat/xmltok_impl.c

Related: https://github.com/goccy/go-graphviz/issues/42#issuecomment-1585616517

**Comment by Alex-Tsekhansky-IBM** [comment]
I'd like to add that the scanner noted the vulnerability in the code used by our group as well (and I assume Ed's issue came up from the same scanner) with the following suggested fix:

Upgrade to version: cmake - 3.19.5,3.17.3,3.22.0;cmake-native - 3.22.0,3.17.3,3.20.1;python3 - 3.8.2. So at least part of the issue may simply be related to a build rather than the code.

Is it possible to rerun the build using the minimum component version indicated, by any chance?
